# Full values: https://github.com/sysdiglabs/charts/blob/main/charts/shield/values.yaml
cluster_config:
  name: {{.Values.pop}}.{{.Values.env}}
  cluster_domain: replicant.ai
  cluster_type: generic # Can be removed - default value as per https://github.com/sysdiglabs/charts/blob/main/charts/shield/values.yaml
  root_namespace: kube-system # Can be removed - default value as per https://github.com/sysdiglabs/charts/blob/main/charts/shield/values.yaml
  tags: {
    project_id: {{.Values.gcp_project}}
  }
sysdig_endpoint:
  region: us4
  access_key_existing_secret: sysdig-access-key
features:
  admission_control:
    enabled: false
  kubernetes_metadata:
    enabled: true
  posture:
    host_posture:
      enabled: true
    cluster_posture:
      enabled: true
  vulnerability_management:
    host_vulnerability_management:
      enabled: true
    container_vulnerability_management:
      enabled: true
    in_use:
      enabled: true
      integration_enabled: true
  detections:
    drift_control:
      enabled: true
    malware_control:
      enabled: true
    ml_policies:
      enabled: true
    kubernetes_audit:
      enabled: true
  investigations:
    activity_audit:
      enabled: true
    live_logs:
      enabled: true
    # Optional, depends on use case, and desired load. Defaults false - https://docs.sysdig.com/en/docs/sysdig-secure/inventory/network/
    # network_security:
    #   enabled: true
    audit_tap:
      enabled: false
    captures:
      enabled: true
    # Optional - https://docs.sysdig.com/en/sysdig-secure/install-agent-components/install-agent-components/kubernetes/install-rapid-response/
    # responding:
    #   rapid_response:
    #     enabled: false
host:
  driver: universal_ebpf
  # # Can be removed - default value as per https://github.com/sysdiglabs/charts/blob/main/charts/shield/values.yaml
  # rbac:
  #   create: true
