apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sysdig-agent-spitfire
  namespace: sysdig-agent
resources:
  - ../../base/sysdig-agent
  - ./sysdig-access-key-sealed.yaml
patches:
  - path: sysdig-shield.yaml
    target:
      kind: HelmRelease
