---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: sysdig-access-key
  namespace: sysdig-agent
spec:
  encryptedData:
    access-key: AgDON7A2yWTk+isZNJlNwkOKyAxQQQx9Z/oInu0Hw3KWQXn/AcCsAFmh5a/SLF/EfHpXoCfmYcQmXjTWbxWk3lgOH5F0X9s9iJ2a637+05cY58CD7s2AM2NHLO7BneJ6ULX5jfewHtZtS2ga6e89xyWXwq94kSGNwE8dUvtPnilmZOHD1QzAuoMErH1KzGtWAk++MjX5G2INOiT+wMnwlJeH1AXySYfwtTQh+tq5vz/3WII3OncwgK7ZIZWdXVexwHSoknM8pJgovVCpLxO+XFuNwppuCH1Vsx3QK1Y01/sUZ/cxS+FKYLbY1P7eAtvlFcyFou/UIEwOIiYHjG7CJDWmQiKJLvw+DHeFRprDgCOqaKpLRzuotMr8dbC/1BtXCmMZ0esn0W6wm/yGvHSBDybFAw36lf5hrdMF4A/rC3XWvZS5SXJhmTK/GslaOAuGiW/4pxhA4g5bXO6mhFsqgK5P6XsanZNhDi9zWXQ5vXWcc5E/ws7zZv9RTOYTAkPDgIk+zMMng9KvOZPueTmgE1xo2ANJzQ84LGBHJ9qt9W3ErqFHQeRFSS/aiMJMoHGRVpU9sQB2DX4IKyNkT/QQ5ILhbR9bZCrjI9MRr0A7Ujx0cMu3auNexhwAPWcYUBOB3DYugL6sTzn0I4E7pGJxod0KZ1xJZzK6yaeJ6yyovanRu/f2tvA6y4Y6gyCHdwAYg20MmQTRJmeHf//XtVPqmIUgYXVTHB+Uhe/z43/YnrhJ2/Fs2c4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: sysdig-access-key
      namespace: sysdig-agent
