---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sysdig-access-key
  namespace: sysdig-agent
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    access-key: AgCEZcByRIDtePP7huEuQ692jdrIcp9eFcH38mHaVUzhBYsZc2ZOIMriZHELbc/pefM7t/xgW+7pcZrffezVpV4LjXpUQcR1bqSSARvL3FojQPt7OqCLGW5Dw0JoFbwh3lp6qQZBzG6S/lu6fn6Aurq+P2BLjjAziDoNXjw7cybeZs6PgAL4pVuREQQn6eC9YufBXIvnT5h7STx9tWFRZ/oRZwSeuo5091ObgTwcfWmET3BS9rQb/Ih0G2K5Xt9iGACxc0psmXXVfebhM163dWDiW0MDopeyRTnXKnyjFoel+OsQKDBwp43CxutqBvhVM0IzoEvnZpsUikd/d7RrHYLxtflhVM5/jKS9iCShKyniz4LHzP9o8kkG4CKAA7jTM8gOrQSE+YHPhWdPYMnGmf6qmWsLwtXXruifE4McbKNxag009nmwhE3sp4vWxsFS39TxDse82V3t3YJIn19P/SqtIaKNGQwcjMf8qr/REmowQ33wqA4pbxKgYLvc8V7eiUu/VhFmThkrLr7bb8GS7rZ4WbHyBKEYXVQh07UIlVM8CKNMnsS0Ls5Jpl9pFSY/oxAz3ZZi2Kq+YmWtEUrAH766giwIQ52U+hIA/trTntrYHqhupO6VVk6kjBcfQVJWkJwl7XuY/wISs1QkX6NYhDNViGE70HjEWRDZIryRUlFLbc+g7Hira5IQJyrHZOFe0NWABURQ8QH7fGJ6L1+DG+m2FeN464N2m2/z2mdhPITIHYNK6Ds=
  template:
    metadata:
      name: sysdig-access-key
      namespace: sysdig-agent
