apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-sysdig-helm-release
  namespace: sysdig-agent
spec:
  interval: 10m
  chart:
    spec:
      chart: sysdig-deply
      version: "1.65.5"
      sourceRef:
        kind: HelmRepository
        name: flux-sysdig-helm-repo
        namespace: sysdig-agent
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: sysdig-agent-values