---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sysdig-access-key
  namespace: sysdig-agent
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    access-key: AgAKjIXqAqWOqiobkGhDBYIg6/UJhuX4fzXhyllBv4H4O1nBXljQhcumkhkrtM4yZ0bIGyjlsKzy5HUSdKMtX+3T+Mm/QbqYYiqIsI404Q0jkcHjOtN/XtA/+Qftdmwr1bi9ZH252G/fIr687TlvSiBJHwEedoQSK2r7P5dnOV7rOVLqIZUONMGigTAz2ijM5sdvnlhwDKs1FiFgtIJYGBqUw0iZev0zVP8aZO245eVu6QV6mbb2JSrC0VKyqj1x0WaQFiWNazovROEMcBS1bvU/SdxYjxJHwhgMsTCj6p2Lr7H+TxhVNYmZqF6BMbO+RrMLN4G5+XBuUmyrs3GrKO/n3VtuiexHVl1a3vOEJfC7mH632SlFrfO9YLpCgU17/ulTuLkpWnYY4NoYor4tWigvjtACIi+ev/QZfF3H2tnOeSNWZZSq4HpYINlhoTubQWNrlIo9wVl4ejm/j+A9rqDQGWjdGUDmOJrqZodYB6C3Pwq8a5Mqn8RiH0zZfsgLyXf+wmUObfB8VETbiJt2/a9pUGdImbWJiMV/Nc1ymJiqxyLuPWT00V3blr0ZVhh7pGqIFlAsLG2P3RiooVqo3aPDqqjahKCDKt/jHlkKIm+EI8XM4JF/F00RrQ5gpbdFQXDzqnppM9WHT7TDL6+RUWOiKN9H4VemDzNl9N0WFlH33m7EVjFEdRO10FtMfuI+dult68QhEGMbFsEwKxa4W4TxHwVoFOtyjkl4qu7rKcdJoii3HhY=
  template:
    metadata:
      creationTimestamp: null
      name: sysdig-access-key
      namespace: sysdig-agent
