apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-sysdig-helm-release
  namespace: sysdig-agent
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: sysdig-deply
      version: "1.65.5"
      sourceRef:
        kind: HelmRepository
        name: flux-sysdig-helm-repo
        namespace: sysdig-agent
      interval: 5m
  releaseName: sysdig
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: sysdig-agent-values-296ff4825k
