apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-darkstar
  namespace: flux-system
resources:
- ../base/cilium.yaml
- cilium.yaml
- ../base/sealed-secrets.yaml