apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
  interval: 1h0m0s
  releaseName: metallb
  targetNamespace: metallb
  install:
    crds: Create
  upgrade:
    crds: CreateReplace