---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sysdig-shield-helm-release
  namespace: sysdig-agent
spec:
  interval: 10m
  values:
    cluster_config:
      name: spitfire
      tags:
        cluster_type: talos
        environment: production
        helm-chart: shield
