---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: sysdig-access-key
  namespace: sysdig-agent
spec:
  encryptedData:
    access-key: AgA0B68G+9CRSmUdkzDDw3puslE0O/Sp81h9Uwa/j3GqIK/T5Tsq1kbx9o0N9ztSS0POvnQbK917Qw+txgXbZbA8l4uUqg8u797O+lrNpngDd/LjIzFAERbOPtNY02kti6Yn1ZpArr3EOSX9PHGZeOqHheVZvfQz1KozR9NK30eJUs/KnVOcd9NZRyC0tuD6hTW+4/a6KF0dp30Dr0C5yfscvRrmSlV62XcNmk8SVvE2KPWL74kqUkJIpDlHt+8tfGwJII5lUZqlP1QF5nP0LFhgfOcmjBXf/6hKC8X0eGfCXZqj8FCPbKWqgVw1OmYh14NbxYYDATrvqeu4bvlvHeIMjVmBMbcBcEJT/zVvAW0TTsnlxwemnO4A1g20Wh/8go2c1fjBqKLHSIPtYgJ7XC5TA9I12tBzejfK74e0tDZBzpiNswRdr2H7IW6fWQCE+a8ju0sF7ZI/tsC3i/AYZJprZh9jUiXQy21L7BlTwjh7G23fUss88m9rc/AUZcgog6z2OiDlc3Z19/MlFo6vWUvbIq0a7nvHW5yL3jox8qmmIEE3KPWGiV/NWemgqOxeO5FdzfU0j3e9i3qsflUdeLo+o+Da6kVpdbN3Ua++Ob8FhOkiUCuzJOGjmToIk7Hmz2Pmkaw2W/V8H3I8A7S/pXNzmDyUnKNJ6SMjJPzh3HzRPnKM4U9LCJErDRJdv1T+8EvVxhyLVqQaU2qxp4Eow1OhWH9HrVOmZLu4sKL+cQkAYQsXSyw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: sysdig-access-key
      namespace: sysdig-agent
