---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: sysdig-access-key
  namespace: sysdig-agent
spec:
  encryptedData:
    access-key: AgAhSB5b5545Sr/kmoc/ZfHFcuQy/PniVq6Nb/14we65sjrtbeWRQb4eCHcZZ0QY0Yv+Ih76tjCmEQW++iK55wecEa6oYKTcVu/tjG8GKaidqj9j4EBwmog0T3N9HKVV49jTLFSr15KNMPXl5M/AHe3PdAmtw/6JWcBEp6ilTXj78xYbDA3EV7oY5OZHSEZRH+ankVGv+8FKB3fxmmhGUGVWYdfGoRyVwpagVaM6U/hlPgTTFn9GZPl+h3RQhAxlPWDvh1iabQ5C5JXCIDx0fzSOjI7HhobkjyhvF9pU2bGw2mlDP38WU3JJCzl7miDTFTavj5YPjKaDhsQ5hneQn580wkL5OnKfw/1xA0P8GFl2+2YrIlgowC/GeyF4e9c7XijlMPweIPQHjyQY0tzJknzN30rFty5P7YgNjIPZb+hnovjUtQ9PCuWUgHG5LVTFa9n1/DMfj0M7PlB8jDjAjCg9JZA5P1Iml6FQ+fzzFWyyRwzkxsXDNA221KZTPgvOYXaLii4PxC/FeTJSvz32NBRHIBG1vP+oDTUbXtKJVgmOQlpPIsZGWWVzrkepCoJvVPXm/r1PWTfHNlmh5IwbzH7ZM/B8oJhfhpf0lXtKID7o5axk+nuCmUwL+HcDGKPHlI8e1VbK18wU8pZyZk9tXeul13VTqIdQaJyHVW6OLk9a+7/zzJauVQOSVcD4nTnUkD2yOb5fQyDnLnkuuiRuBGBoy4P/bFXyz+IpnLWgRJj4s9pseyw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: sysdig-access-key
      namespace: sysdig-agent
