---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: sysdig-access-key
  namespace: sysdig-agent
spec:
  encryptedData:
    access-key: AgA8TeqZnb8GdUGWq7iRhdj5nCaflR2Pcel6vtwBo0XXpNF4UHK/yfV8YbRPhvQTBy+w+/n9ysbKSflfHr3PG7ZBZU5aQJHATVluH83eOkKbZ+m62MGdenf1Iaj9uKolx4Jqe3X+GWt8CREG2aV1xomGy1OWurLHuRTk7Eu3TZwTI9L6bBV0CndknnP6ZBmJrHmtmUB4xrcMXiHAofIz4dg2rQkMVCnbMJHrUkPlth8pDzblW35UJJqYOs4mBnLSa5dIGeUjRwxN6OCGkuGhHmd/cK6xG1OxgkU9BsDfxxK7csS8O1j743Yq/yU5JbKpSnQX4EnjaY6FkNPmHuDveek73nq9n+krmlZM/wpkXkE8P0bbTE+9NVbf68s42zTx8aP2B2wThkaeS13ox8QGl/Qc8aJyJuuzA7l2czL3Piiwx7tXsYsAJSZbfy4CQ7U4pDzVS6tLunXdSu+jYRv1kF0Ejn5Pl5ZLpa7Gc6NP04iNhftxgDYr73/IcUSWjbV4Ievy+veI6PyT5sdEmO5zr86tWjfbz5YqBomGaO9ig3zGyf/gXbOqpuZvp1gYy+Wfw8/4AyOpz7CibkXcAFkF1XCDuQGdE3sfMPbQIDDrbG7KEqEY+/y1HzMneMiJDCugcEp4HOWXgos/FwrEMSr55/wUwglOEc98w3dfS3DfXJXTrsl28AZ9kYVyp8v1qLsjpPYgZqau/iBonG5W1c+Z9FAAwV5feLvsc7iO4jUeq4CvxgBLFFg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: sysdig-access-key
      namespace: sysdig-agent
