apiVersion: v1
kind: Namespace
metadata:
  name: sysdig-agent
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: sysdig-access-key
  namespace: sysdig-agent
spec:
  encryptedData:
    access-key: AgA5rDBrtIzkwB1satAPU8GNZWlJQexDxBrzppLXbuNa0ZkK1PUQNZY4qVAS6+kKyzPTQvL/05GFOdHkiR33aJO4WwoMP0mV5vHWPdqJG7xNWmJKMKeDLRReGacosWP3xXm8xX7lpfyKSDo9NkpXJRLrYDIdI73ila6+Y2rhaZPgT97sDE22bK03MiHXb4Tr9X14N7OqgMBlK5diUQ2Vn8yPtm8ss3igb6IJM8lP6uw8dMOwzdE41AmyMMkXP9ANn3kBfsiEimyKs3QXy6Hd8HrmrMbSvud6DucQHgT6kAiQt/MnJwjLocgd/D38Oysg2to1Sx3DhluOlzwHHafynqhe22xAZUxxbXXXSSMJdfNC1jCb7fP1dIc3iSCnmRHQ5+SVEMNNjKfhpZ4EK4kxQPLPkmOl5qeklukeyJiwtqEgtlJSlYHQRy0FoExVSoO1/XQ4gOxq8RK4bV8p1mlw7GSdTvrC7jWFL2CimiHyODAVGySnk8SJQcxuhm17whepz+QxJe2KDjjc2cFr6Nznf1wYidVgRxFz1JbuoU5CfPudJHsBHmQ9VrsdaGyH9HwBHPPl9XCQDQVvK78KfJIs202Yx4et5yqaKWJfea0ZWl+v6tdf3EHfOMz/MkA3kdYFGOs+rLFaMwsx3mbwUkr9I7Qlf4o/kK1Z3/Ew/FnA0VQq52B5AFPEzrWkGfJ/xuG85fTwtdQ/mKKS238aC2a2sMEeTX9R7c64CfB1vfAJpMlqKT3yBcg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: sysdig-access-key
      namespace: sysdig-agent
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flux-sysdig-helm-repo
  namespace: sysdig-agent
spec:
  interval: 1h0m0s
  url: https://charts.sysdig.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-sysdig-helm-release
  namespace: sysdig-agent
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: shield
      sourceRef:
        kind: HelmRepository
        name: flux-sysdig-helm-repo
        namespace: sysdig-agent
      interval: 5m
  releaseName: sysdig
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    ## Create a values.yaml file with the following:
    sysdig_endpoint:
      region: us2
      # access_key: xxxxxx
      access_key_existing_secret: sysdig-access-key
    features:
      admission_control:
        # Enable the admission control feature
        enabled: false
        # Deny the admission of the pod if an error occurs
        deny_on_error: false
        # Enable the dry run mode
        dry_run: true
        container_vulnerability_management:
          # Enable the container vulnerability management feature on the admission control
          enabled: false
      kubernetes_metadata:
        # Enable the Kubernetes Metadata feature on cluster shield
        enabled: false
      posture:
        host_posture:
          enabled: true
        cluster_posture:
          enabled: true
      vulnerability_management:
        host_vulnerability_management:
          enabled: true
        container_vulnerability_management:
          enabled: true
        in_use:
          enabled: true
      detections:
        drift_control:
          enabled: true
        malware_control:
          enabled: true
        ml_policies:
          enabled: true
        kubernetes_audit:
          # Enable the Kubernetes Audit feature on cluster shield
          enabled: true
      investigations:
        activity_audit:
          enabled: true
        live_logs:
          enabled: true
        network_security:
          enabled: true
        audit_tap:
          enabled: false
        captures:
          enabled: true
        event_forwarder:
          enabled: false
      responding:
        rapid_response:
          enabled: false
      monitoring:
        app_checks:
          enabled: false
        java_management_extensions:
          enabled: false
        prometheus:
          enabled: true
        statsd:
          enabled: true
    # host:
    #   resources:
    #     kmodule:
    #       limits:
    #         cpu: 1000m
    #         memory: 1Gi
    #       requests:
    #         cpu: 250m
    #         memory: 384Mi
    #     shield:
    #       limits:
    #         cpu: 1000m
    #         memory: 1Gi
    #       requests:
    #         cpu: 250m
    #         memory: 384Mi
    cluster:
      # The mode in which the cluster shield should run (Accepted Values: single-process, multi-process)
      run_mode: multi-process
      # resources:
      #   requests:
      #     cpu: 500m
      #     memory: 512Mi
      #   limits:
      #     cpu: 1500m
      #     memory: 1536Mi
      # Automatically adds the Prometheus annotations to the Cluster Shield pods
      enable_prometheus_scraping: true
