apiVersion: v1
kind: Namespace
metadata:
  name: sysdig-agent
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sysdig-shield-helmrepo
  namespace: sysdig-agent
spec:
  interval: 15m
  url: https://charts.sysdig.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sysdig-shield-helm-release
  namespace: sysdig-agent
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: shield
      version: 0.6.3
      sourceRef:
        kind: HelmRepository
        name: sysdig-shield-helmrepo
        namespace: sysdig-agent
      interval: 5m
  releaseName: sysdig
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    ## Create a values.yaml file with the following:
    sysdig_endpoint:
      region: us2
      access_key_existing_secret: sysdig-access-key
    features:
      admission_control:
        enabled: false
      kubernetes_metadata:
        enabled: true
      posture:
        host_posture:
          enabled: true
        cluster_posture:
          enabled: true
      vulnerability_management:
        host_vulnerability_management:
          enabled: true
        container_vulnerability_management:
          enabled: true
        in_use:
          enabled: true
          integration_enabled: true
      detections:
        drift_control:
          enabled: true
        malware_control:
          enabled: true
        ml_policies:
          enabled: true
        kubernetes_audit:
          enabled: true
      investigations:
        activity_audit:
          enabled: true
        live_logs:
          enabled: true
        network_security:
          enabled: true
        audit_tap:
          enabled: true
        captures:
          enabled: true
        responding:
          rapid_response:
            enabled: false
    host:
      driver: universal_ebpf
      privileged: true
    # cluster:
    #   replica_count: 1
    #   additional_settings:
    #     log_level: debug