apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    toolkit.fluxcd.io/tenant: cluster-admin
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name:  flux-traefik-helm-repo
  namespace: traefik
spec:
  interval: 1h0m0s
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-traefik-helm-release
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: flux-traefik-helm-repo
        namespace: traefik
      version: ">=32.0.0"
  interval: 1h0m0s
  releaseName: traefik
  targetNamespace: traefik
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    providers:
      # Disable the Ingress provider (optional)
      # We do not want to use Ingress objects anymore!
      kubernetesIngress:
        enabled: false
      # Enable the GatewayAPI provider
      kubernetesGateway:
        enabled: true
    # Allow the Gateway to expose HTTPRoute from all namespaces
    gateway:
      namespacePolicy: All