apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flux-traefik-helm-repo
  namespace: traefik
spec:
  interval: 1h0m0s
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-traefik-helm-release
  namespace: traefik
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: flux-traefik-helm-repo
        namespace: traefik
      interval: 5m
  releaseName: traefik
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    providers:
      # Disable the Ingress provider (optional)
      # We do not want to use Ingress objects anymore!
      kubernetesIngress:
        enabled: false
      # Enable the GatewayAPI provider
      kubernetesGateway:
        enabled: true
    # Allow the Gateway to expose HTTPRoute from all namespaces
    gateway:
      namespacePolicy: All