apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sysdig-agent
resources:
- sysdig-agent.yaml
configMapGenerator:
  - name: sysdig-agent-values
    files:
      - values.yaml=sysdig-agent-values.yaml
configurations:
  - kustomizeconfig.yaml