---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-sysdig-helm-release
  namespace: sysdig-agent
spec:
  interval: 10m
  values:
    clusterConfig:
      name: darkstar
      tags:
        cluster_type: talos
        environment: production
