apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure-spitfire
  namespace: flux-system
resources:
  - ../base/cilium.yaml
  - cilium.yaml
  - ../base/sealed-secrets.yaml
