apiVersion: v1
kind: Namespace
metadata:
  name: sysdig-agent
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: sysdig-access-key
  namespace: sysdig-agent
spec:
  encryptedData:
    access-key: AgCPDiOBy+jt4kufx/+YGpk/e7831ug6+vuzCPsXc9Gn2fxSLtHTyzurjqUhdTna0C0RQkV1wluOFSUxOMmDGsc7A6cqK+5xJp1jOBZWbgH6CkUqzZ7DxeKorGg52jq8/kIaZ507a0A4v/75Q/TsJlWc6RT/mAXvGcgM4ovejlTRV+EKBdH+aC8uLM/V50SKeDevzfSOoVpyc530zURqaz+HmfQ5yjUYWh6KQYXecPjeyEtO/HQrc89acJbAD2D2rBE0LIidvjdMzt0BWLzpHGMAMw2U6GJd34npu3ADnQVuJuVdJ1kgXfiUXIR+R6lUWXuvEJNyIMuPDkCeym5YnC6J+vfLRvj1KKe5flCJgnZ751VMH8j4D0Ne0FuSvuMxKUR8tTmlBb7hPO0mlr9Y1CNJ1z60uO/AZ0g4pv6AZSfKcN/0WuwnFxUM+pCwvVXk5ftK+m0qYwBG+6+12kkcRCO7b4l1bJyCDRb0JivCCR2wNx0oo0BgXA3kOcA86HBSKU5v1auGr7ouecdBSCna56lJsYfYdCu+ELwZ/G82IEXNwDADqNKuGv8+1etkaSReqdMOjbsWPJ9kzDpkM/3gU3YV2C7QbrApDvXuPhE9xhiWluVj762FZCmg3fw5WnMEoa8o/+L5szekv3UXNnFwH5+V5QOWGGIcXTGuxNt8RJL5nXAMx+f2K0qrraPJf9UW0SAuNt7iiYz7KKApAQb+E7o9F5JEInVWvhTD8FfIblsYXzqr/kM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: sysdig-access-key
      namespace: sysdig-agent
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flux-sysdig-helm-repo
  namespace: sysdig-agent
spec:
  interval: 1h0m0s
  url: https://charts.sysdig.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-sysdig-helm-release
  namespace: sysdig-agent
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: shield
      sourceRef:
        kind: HelmRepository
        name: flux-sysdig-helm-repo
        namespace: sysdig-agent
      interval: 5m
  releaseName: sysdig
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    ## Create a values.yaml file with the following:
    global:
      sysdig_endpoint:
        region: us2
        # accessKey: xxxxxx
        accessKeySecret: sysdig-access-key
      features:
        admission_control:
          # Enable the admission control feature
          enabled: false
          # Deny the admission of the pod if an error occurs
          deny_on_error: false
          # Enable the dry run mode
          dry_run: true
          # The timeout for the admission control feature
          timeout: 10
          # The port that will be used to expose admission control endpoints
          http_port: 8443
          # The list of namespaces that will be excluded from the admission control
          excluded_namespaces: []
          container_vulnerability_management:
            # Enable the container vulnerability management feature on the admission control
            enabled: false

        kubernetes_metadata:
          # Enable the Kubernetes Metadata feature on cluster shield
          enabled: false

        posture:
          host_posture:
            enabled: true
          cluster_posture:
            enabled: true
        vulnerability_management:
          host_vulnerability_management:
            enabled: true
          container_vulnerability_management:
            enabled: true
          in_use:
            enabled: true
        detections:
          drift_control:
            enabled: true
          malware_control:
            enabled: true
          ml_policies:
            enabled: true
          kubernetes_audit:
            # Enable the Kubernetes Audit feature on cluster shield
            enabled: true
        investigations:
          activity_audit:
            enabled: true
          live_logs:
            enabled: true
          network_security:
            enabled: true
          audit_tap:
            enabled: false
          captures:
            enabled: true
          event_forwarder:
            enabled: false
        responding:
          rapid_response:
            enabled: false
        monitoring:
          app_checks:
            enabled: false
          java_management_extensions:
            enabled: false
          prometheus:
            enabled: true
          statsd:
            enabled: true

      host:
        resources:
          kmodule:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 384Mi
          shield:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 384Mi
      cluster:
        # The mode in which the cluster shield should run (Accepted Values: single-process, multi-process)
        run_mode: multi-process
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1500m
            memory: 1536Mi
        # Additional settings to be passed to the cluster shield (overrides the helm generated settings)
        additional_settings:
          log_level: info
          monitoring_port: 8080
        # Automatically adds the Prometheus annotations to the Cluster Shield pods
        enable_prometheus_scraping: true
        # The number of replicas for the cluster shield
        replica_count: 1
