---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-nfs
  namespace: nfs-test
spec:
  nodeSelector:
    "kubernetes.io/os": linux
  securityContext:
    fsGroup: 1000  # Ensure the volume is writable by the group
  containers:
    - image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
      name: nginx-nfs
      command:
        - "/bin/bash"
        - "-c"
        - |
          set -euo pipefail
          while true; do
            echo $(date) >> /mnt/nfs/outfile
            sleep 1
          done
      volumeMounts:
        - name: persistent-storage
          mountPath: "/mnt/nfs"
          readOnly: false
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - "ALL"
        runAsNonRoot: true
        runAsUser: 1000  # Specify a non-root user ID
        runAsGroup: 1000  # Specify a non-root group ID
        seccompProfile:
          type: RuntimeDefault
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: pvc-nfs-dynamic